language: python
python:
  - '3.6'
stages:
  - build
  - test
jobs:
  include:
    - stage: build
      script:
        - python setup.py install
    - stage: test
      script:
        - flake8 bind/ tests/
        - mypy bind/ tests/
        - python -m unittest